### ISSUE TITLE
Ex 4.2.2 Mistake in solution

### ISSUE THREAD

**Issue by d0nghyunkang** [ulfaslak/sds_tddl_2020#2]
### Issue summary
I think there's a mistake in the solution. It does not contain any L2 regularization although the instruction requires so.

### Code and output (if applicable)

The given solution code is like below:

```
# Define model
model_regul = Sequential()
model_regul.add(Dense(input_dim=2, output_dim=100, activation='relu'))
model_regul.add(Dense(input_dim=100, output_dim=100, activation='relu'))
model_regul.add(Dense(input_dim=100, output_dim=1, activation='sigmoid'))
model_regul.compile(optimizer=keras.optimizers.Adam(learning_rate=1e-2, decay=1e-1), loss='mse', metrics=['accuracy'])
model_regul.fit(x, y, nb_epoch=1000, verbose=1)
```

However, I think one of the Keras layers should include a regularizing parameters as follows:

```
model_regul.add(Dense(1024, input_shape=(2,), activation='relu', 
                kernel_regularizer=regularizers.l2(0.01)))
```

The difference is **kernel_regularizer=regularizers.l2(0.01)**.

**Comment by ulfaslak** [comment]
The `decay` parameter implements L2 reg. Works, but not super clear (and not documented in keras it seems) so I understand your confusion.
